version: 2.1

jobs:
  build:
    environment: 
      NIBI_PATH: /tmp/nibi_path
    docker:
      - image: "cimg/base:2023.06-20.04"
    steps:
      - checkout
      - run:
          name: Update and uprade
          command: 'sudo apt update && sudo apt upgrade'
      - run:
          name: Install tools and libs
          command: 'sudo apt install -y git gcc-9 g++-9 pkg-config build-essential cmake python3 libffi-dev valgrind'
      - run:
          name: Construct NIBI_PATH
          command: 'mkdir /tmp/nibi_path'
      - run:
          name: Build and install libnibi, and nibi
          command: 'python3 commander.py -n'
      - run:
          name: ldconfig
          command: 'sudo ldconfig'
      - run:
          name: Build and install modules
          command: 'python3 commander.py -m'
      - run:
          name: Check all modules
          command: 'python3 commander.py -c'
      - run:
          name: Run NIBI script tests
          command: 'python3 commander.py -t'
      - run:
          name: Run NIBI valgrind tests
          command: 'python3 commander.py -v'
