version: 2.1

jobs:
  build:
    environment: 
      NIBI_PATH: /tmp/nibi_path
    docker:
      - image: "cimg/base:2023.06-20.04"
    steps:
      - checkout
      - run:
          name: Construct NIBI_PATH
          command: 'mkdir /tmp/nibi_path'
      - run:
          name: Update and uprade
          command: 'sudo apt update && sudo apt upgrade'
      - run:
          name: Install tools and libs
          command: 'sudo apt install -y git gcc-10 g++-10 pkg-config build-essential python3 libfmt-dev'
      - run:
          name: Build
          command: 'make -j3'
      - run:
          name: Run tests
          command: 'make test'
