# Ubuntu Base
FROM ubuntu:22.04

# Installing essencial packages for python and C/C++
RUN apt-get update && apt-get install -y git g++-9 pkg-config build-essential cmake python3 libffi-dev sudo

# Workding DIR
WORKDIR /NIBI

# Copying the files
COPY ../ .

# Set NIBI_PATH where nibi modules will be installed
RUN mkdir /NIBI/home
ENV NIBI_PATH=/NIBI/home

# Running commander.py with -n -m flags
RUN python3 commander.py -s -n -m

# Copy the .so for nibi
COPY nibi/build/lib/libnibi.so /usr/lib
RUN ldconfig

# Open nibi REPL
ENTRYPOINT ["nibi"]
