#ifndef LIBNIBI_VERSION_
#define LIBNIBI_VERSION_

#define LIBNIBI_MAJOR_VERSION (0)
#define LIBNIBI_MINOR_VERSION (1)
#define LIBNIBI_PATCH_VERSION (0)
#define LIBNIBI_VERSION "0.1.0"

#endif // LIBNIBI_VERSION_
