#pragma once

#include <string>
#include <unordered_map>
#include <vector>

namespace app {
namespace completions {

inline std::unordered_map<std::string, std::vector<std::string>>
get_completion_map() {
  return {
      {"(:", {"(:= "}},
      {"(:=", {"(:= "}},

      {"(a",
       {"(assert ", "(alias ", "(at ", "(and ", "(always ", "(assert_eq ",
        "(assert_neq "}},
      {"(al", {"(alias ", "(always "}},
      {"(ali", {"(alias "}},
      {"(alia", {"(alias "}},
      {"(alw", {"(always "}},
      {"(alwa", {"(always "}},
      {"(alway", {"(always "}},
      {"(always", {"(always "}},
      {"(as", {"(assert ", "(assert_eq ", "(assert_neq "}},
      {"(ass", {"(assert ", "(assert_eq ", "(assert_neq "}},
      {"(asse", {"(assert ", "(assert_eq ", "(assert_neq "}},
      {"(asser", {"(assert ", "(assert_eq ", "(assert_neq "}},
      {"(assert", {"(assert "}},
      {"(assert_", {"(assert_eq ", "(assert_neq "}},
      {"(assert_e", {"(assert_eq "}},
      {"(assert_eq", {"(assert_eq "}},
      {"(assert_n", {"(assert_neq "}},
      {"(assert_ne", {"(assert_neq "}},
      {"(assert_neq", {"(assert_neq "}},
      {"(at", {"(at "}},
      {"(an", {"(and "}},
      {"(and", {"(and "}},

      {"(b",
       {"(bw-lsh ", "(bw-rsh ", "(bw-and ", "(bw-or ", "(bw-xor ", "(bw-not "}},
      {"(bw",
       {"(bw-lsh ", "(bw-rsh ", "(bw-and ", "(bw-or ", "(bw-xor ", "(bw-not "}},
      {"(bw-",
       {"(bw-lsh ", "(bw-rsh ", "(bw-and ", "(bw-or ", "(bw-xor ", "(bw-not "}},
      {"(bw-l", {"(bw-lsh "}},
      {"(bw-ls", {"(bw-lsh "}},
      {"(bw-lsh", {"(bw-lsh "}},
      {"(bw-r", {"(bw-rsh "}},
      {"(bw-rs", {"(bw-rsh "}},
      {"(bw-rsh", {"(bw-rsh "}},
      {"(bw-a", {"(bw-and "}},
      {"(bw-an", {"(bw-and "}},
      {"(bw-and", {"(bw-and "}},
      {"(bw-o", {"(bw-or "}},
      {"(bw-or", {"(bw-or "}},
      {"(bw-x", {"(bw-xor "}},
      {"(bw-xo", {"(bw-xor "}},
      {"(bw-xor", {"(bw-xor "}},
      {"(bw-n", {"(bw-not "}},
      {"(bw-no", {"(bw-not "}},
      {"(bw-not", {"(bw-not "}},

      {"(c", {"(clone ", "(char "}},
      {"(ch", {"(char "}},
      {"(cha", {"(char "}},
      {"(char", {"(char "}},
      {"(cl", {"(clone "}},
      {"(clo", {"(clone "}},
      {"(clon", {"(clone "}},
      {"(clone", {"(clone "}},

      {"(d",
       {"(drop ", "(dict ", "(defer ", "(dict_has_key ", "(dict_empty ",
        "(dict_key_from_value "}},
      {"(de", {"(defer "}},
      {"(def", {"(defer "}},
      {"(defe", {"(defer "}},
      {"(defer", {"(defer "}},
      {"(di",
       {"(dict ", "(dict_has_key ", "(dict_empty ", "(dict_key_from_value "}},
      {"(dic",
       {"(dict ", "(dict_has_key ", "(dict_empty ", "(dict_key_from_value "}},
      {"(dict",
       {"(dict ", "(dict_has_key ", "(dict_empty ", "(dict_key_from_value "}},
      {"(dict_", {"(dict_has_key ", "(dict_empty ", "(dict_key_from_value "}},
      {"(dict_h", {"(dict_has_key "}},
      {"(dict_ha", {"(dict_has_key "}},
      {"(dict_has", {"(dict_has_key "}},
      {"(dict_has_", {"(dict_has_key "}},
      {"(dict_has_k", {"(dict_has_key "}},
      {"(dict_has_ke", {"(dict_has_key "}},
      {"(dict_has_key", {"(dict_has_key "}},
      {"(dict_e", {"(dict_empty "}},
      {"(dict_em", {"(dict_empty "}},
      {"(dict_emp", {"(dict_empty "}},
      {"(dict_empt", {"(dict_empty "}},
      {"(dict_empty", {"(dict_empty "}},
      {"(dict_k", {"(dict_key_from_value "}},
      {"(dict_ke", {"(dict_key_from_value "}},
      {"(dict_key", {"(dict_key_from_value "}},
      {"(dict_key_", {"(dict_key_from_value "}},
      {"(dict_key_f", {"(dict_key_from_value "}},
      {"(dict_key_fr", {"(dict_key_from_value "}},
      {"(dict_key_fro", {"(dict_key_from_value "}},
      {"(dict_key_from", {"(dict_key_from_value "}},
      {"(dict_key_from_", {"(dict_key_from_value "}},
      {"(dict_key_from_v", {"(dict_key_from_value "}},
      {"(dict_key_from_va", {"(dict_key_from_value "}},
      {"(dict_key_from_val", {"(dict_key_from_value "}},
      {"(dict_key_from_valu", {"(dict_key_from_value "}},
      {"(dict_key_from_value", {"(dict_key_from_value "}},
      {"(dr", {"(drop "}},
      {"(dro", {"(drop "}},
      {"(drop", {"(drop "}},

      {"(e", {"(exit ", "(eval ", "(eq ", "(extern-call ", "(exchange "}},
      {"(ev", {"(eval "}},
      {"(eva", {"(eval "}},
      {"(eval", {"(eval "}},
      {"(eq", {"(eq "}},
      {"(ex", {"(exit ", "(extern-call ", "(exchange "}},
      {"(exi", {"(exit "}},
      {"(exit", {"(exit "}},
      {"(ext", {"(extern-call "}},
      {"(exte", {"(extern-call "}},
      {"(exter", {"(extern-call "}},
      {"(extern", {"(extern-call "}},
      {"(extern-", {"(extern-call "}},
      {"(extern-c", {"(extern-call "}},
      {"(extern-ca", {"(extern-call "}},
      {"(extern-cal", {"(extern-call "}},
      {"(extern-call", {"(extern-call "}},
      {"(exc", {"(exchange "}},
      {"(exch", {"(exchange "}},
      {"(excha", {"(exchange "}},
      {"(exchan", {"(exchange "}},
      {"(exchang", {"(exchange "}},
      {"(exchange", {"(exchange "}},

      {"(f",
       {"(fn ", "(float ", "(f32 ", "(f64 ", "(filter ", "(filter_even ",
        "(filter_odd ", "(forever "}},
      {"(f3", {"(f32 "}},
      {"(f32", {"(f32 "}},
      {"(f6", {"(f64 "}},
      {"(f64", {"(f64 "}},
      {"(fi", {"(filter ", "(filter_even ", "(filter_odd "}},
      {"(fil", {"(filter ", "(filter_even ", "(filter_odd "}},
      {"(filt", {"(filter ", "(filter_even ", "(filter_odd "}},
      {"(filte", {"(filter ", "(filter_even ", "(filter_odd "}},
      {"(filter", {"(filter ", "(filter_even ", "(filter_odd "}},
      {"(filter_", {"(filter_even ", "(filter_odd "}},
      {"(filter_e", {"(filter_even "}},
      {"(filter_ev", {"(filter_even "}},
      {"(filter_eve", {"(filter_even "}},
      {"(filter_even", {"(filter_even "}},
      {"(filter_o", {"(filter_odd "}},
      {"(filter_od", {"(filter_odd "}},
      {"(filter_odd", {"(filter_odd "}},
      {"(fl", {"(float "}},
      {"(flo", {"(float "}},
      {"(floa", {"(float "}},
      {"(float", {"(float "}},
      {"(fn", {"(fn "}},
      {"(fo", {"(forever "}},
      {"(for", {"(forever "}},
      {"(fore", {"(forever "}},
      {"(forev", {"(forever "}},
      {"(foreve", {"(forever "}},
      {"(forever", {"(forever "}},

      {"(i",
       {"(if ",          "(int ",        "(i8 ",           "(i16 ",
        "(i32 ",         "(i64 ",        "(import ",       "(iter ",
        "(is_nil ",      "(is_dict ",    "(is_i8 ",        "(is_i16 ",
        "(is_i32 ",      "(is_i64 ",     "(is_u8 ",        "(is_u16 ",
        "(is_u32 ",      "(is_u64 ",     "(is_f32 ",       "(is_f64 ",
        "(is_ptr ",      "(is_int ",     "(is_float ",     "(is_char ",
        "(is_string ",   "(is_bool ",    "(is_data_list ", "(is_ins_list ",
        "(is_list ",     "(is_symbol ",  "(is_fn ",        "(is_env ",
        "(is_aberrant ", "(is_unknown ", "(is_numeric "}},
      {"(i8", {"(i8 "}},
      {"(i1", {"(i16 "}},
      {"(i16", {"(i16 "}},
      {"(i3", {"(i32 "}},
      {"(i32", {"(i32 "}},
      {"(i6", {"(i64 "}},
      {"(i64", {"(i64 "}},
      {"(if", {"(if "}},
      {"(im", {"(import \""}},
      {"(imp", {"(import \""}},
      {"(impo", {"(import \""}},
      {"(impor", {"(import \""}},
      {"(import", {"(import \""}},
      {"(in", {"(int "}},
      {"(int", {"(int "}},
      {"(is",
       {"(is_nil ",      "(is_dict ",    "(is_i8 ",        "(is_i16 ",
        "(is_i32 ",      "(is_i64 ",     "(is_u8 ",        "(is_u16 ",
        "(is_u32 ",      "(is_u64 ",     "(is_f32 ",       "(is_f64 ",
        "(is_ptr ",      "(is_int ",     "(is_float ",     "(is_char ",
        "(is_string ",   "(is_bool ",    "(is_data_list ", "(is_ins_list ",
        "(is_list ",     "(is_symbol ",  "(is_fn ",        "(is_env ",
        "(is_aberrant ", "(is_unknown ", "(is_numeric "}},
      {"(is_",
       {"(is_nil ",      "(is_dict ",    "(is_i8 ",        "(is_i16 ",
        "(is_i32 ",      "(is_i64 ",     "(is_u8 ",        "(is_u16 ",
        "(is_u32 ",      "(is_u64 ",     "(is_f32 ",       "(is_f64 ",
        "(is_ptr ",      "(is_int ",     "(is_float ",     "(is_char ",
        "(is_string ",   "(is_bool ",    "(is_data_list ", "(is_ins_list ",
        "(is_list ",     "(is_symbol ",  "(is_fn ",        "(is_env ",
        "(is_aberrant ", "(is_unknown ", "(is_numeric "}},
      {"(is_n", {"(is_nil ", "(is_numeric "}},
      {"(is_ni", {"(is_nil "}},
      {"(is_nil", {"(is_nil "}},
      {"(is_nu", {"(is_numeric "}},
      {"(is_num", {"(is_numeric "}},
      {"(is_nume", {"(is_numeric "}},
      {"(is_numer", {"(is_numeric "}},
      {"(is_numeri", {"(is_numeric "}},
      {"(is_numeric", {"(is_numeric "}},
      {"(is_d", {"(is_dict ", "(is_data_list "}},
      {"(is_di", {"(is_dict "}},
      {"(is_dic", {"(is_dict "}},
      {"(is_dict", {"(is_dict "}},
      {"(is_da", {"(is_data_list "}},
      {"(is_dat", {"(is_data_list "}},
      {"(is_data", {"(is_data_list "}},
      {"(is_data_", {"(is_data_list "}},
      {"(is_data_l", {"(is_data_list "}},
      {"(is_data_li", {"(is_data_list "}},
      {"(is_data_lis", {"(is_data_list "}},
      {"(is_data_list", {"(is_data_list "}},
      {"(is_i",
       {"(is_i8 ", "(is_i16 ", "(is_i32 ", "(is_i64 ", "(is_int ",
        "(is_ins_list "}},
      {"(is_i8", {"(is_i8 "}},
      {"(is_i1", {"(is_i16 "}},
      {"(is_i16", {"(is_i16 "}},
      {"(is_i3", {"(is_i32 "}},
      {"(is_i32", {"(is_i32 "}},
      {"(is_i6", {"(is_i64 "}},
      {"(is_i64", {"(is_i64 "}},
      {"(is_in", {"(is_int ", "(is_ins_list "}},
      {"(is_int", {"(is_int "}},
      {"(is_ins", {"(is_ins_list "}},
      {"(is_ins_", {"(is_ins_list "}},
      {"(is_ins_l", {"(is_ins_list "}},
      {"(is_ins_li", {"(is_ins_list "}},
      {"(is_ins_lis", {"(is_ins_list "}},
      {"(is_ins_list", {"(is_ins_list "}},
      {"(is_u",
       {"(is_u8 ", "(is_u16 ", "(is_u32 ", "(is_u64 ", "(is_unknown "}},
      {"(is_u8", {"(is_u8 "}},
      {"(is_u1", {"(is_u16 "}},
      {"(is_u16", {"(is_u16 "}},
      {"(is_u3", {"(is_u32 "}},
      {"(is_u32", {"(is_u32 "}},
      {"(is_u6", {"(is_u64 "}},
      {"(is_u64", {"(is_u64 "}},
      {"(is_un", {"(is_unknown "}},
      {"(is_unk", {"(is_unknown "}},
      {"(is_unkn", {"(is_unknown "}},
      {"(is_unkno", {"(is_unknown "}},
      {"(is_unknow", {"(is_unknown "}},
      {"(is_unknown", {"(is_unknown "}},
      {"(is_f", {"(is_f32 ", "(is_f64 ", "(is_float ", "(is_fn "}},
      {"(is_f3", {"(is_f32 "}},
      {"(is_f32", {"(is_f32 "}},
      {"(is_f6", {"(is_f64 "}},
      {"(is_f64", {"(is_f64 "}},
      {"(is_fl", {"(is_float "}},
      {"(is_flo", {"(is_float "}},
      {"(is_floa", {"(is_float "}},
      {"(is_float", {"(is_float "}},
      {"(is_fn", {"(is_fn "}},
      {"(is_p", {"(is_ptr "}},
      {"(is_pt", {"(is_ptr "}},
      {"(is_ptr", {"(is_ptr "}},
      {"(is_c", {"(is_char "}},
      {"(is_ch", {"(is_char "}},
      {"(is_cha", {"(is_char "}},
      {"(is_char", {"(is_char "}},
      {"(is_s", {"(is_string ", "(is_symbol "}},
      {"(is_st", {"(is_string "}},
      {"(is_str", {"(is_string "}},
      {"(is_stri", {"(is_string "}},
      {"(is_strin", {"(is_string "}},
      {"(is_string", {"(is_string "}},
      {"(is_sy", {"(is_symbol "}},
      {"(is_sym", {"(is_symbol "}},
      {"(is_symb", {"(is_symbol "}},
      {"(is_symbo", {"(is_symbol "}},
      {"(is_symbol", {"(is_symbol "}},
      {"(is_b", {"(is_bool "}},
      {"(is_bo", {"(is_bool "}},
      {"(is_boo", {"(is_bool "}},
      {"(is_bool", {"(is_bool "}},
      {"(is_l", {"(is_list "}},
      {"(is_li", {"(is_list "}},
      {"(is_lis", {"(is_list "}},
      {"(is_list", {"(is_list "}},
      {"(is_e", {"(is_env "}},
      {"(is_en", {"(is_env "}},
      {"(is_env", {"(is_env "}},
      {"(is_a", {"(is_aberrant "}},
      {"(is_ab", {"(is_aberrant "}},
      {"(is_abe", {"(is_aberrant "}},
      {"(is_aber", {"(is_aberrant "}},
      {"(is_aberr", {"(is_aberrant "}},
      {"(is_aberra", {"(is_aberrant "}},
      {"(is_aberran", {"(is_aberrant "}},
      {"(is_aberrant", {"(is_aberrant "}},
      {"(it", {"(iter "}},
      {"(ite", {"(iter "}},
      {"(iter", {"(iter "}},

      {"(l",
       {"(loop ", "(len ", "(list_back ", "(list_nth ", "(list_contains ",
        "(list_execute "}},
      {"(le", {"(len "}},
      {"(len", {"(len "}},
      {"(li",
       {"(list_back ", "(list_nth ", "(list_contains ", "(list_execute "}},
      {"(lis",
       {"(list_back ", "(list_nth ", "(list_contains ", "(list_execute "}},
      {"(list",
       {"(list_back ", "(list_nth ", "(list_contains ", "(list_execute "}},
      {"(list_",
       {"(list_back ", "(list_nth ", "(list_contains ", "(list_execute "}},
      {"(list_b", {"(list_back "}},
      {"(list_ba", {"(list_back "}},
      {"(list_bac", {"(list_back "}},
      {"(list_back", {"(list_back "}},
      {"(list_n", {"(list_nth "}},
      {"(list_nt", {"(list_nth "}},
      {"(list_nth", {"(list_nth "}},
      {"(list_c", {"(list_contains "}},
      {"(list_co", {"(list_contains "}},
      {"(list_con", {"(list_contains "}},
      {"(list_cont", {"(list_contains "}},
      {"(list_conta", {"(list_contains "}},
      {"(list_contai", {"(list_contains "}},
      {"(list_contain", {"(list_contains "}},
      {"(list_contains", {"(list_contains "}},
      {"(list_e", {"(list_execute "}},
      {"(list_ex", {"(list_execute "}},
      {"(list_exe", {"(list_execute "}},
      {"(list_exec", {"(list_execute "}},
      {"(list_execu", {"(list_execute "}},
      {"(list_execut", {"(list_execute "}},
      {"(list_execute", {"(list_execute "}},
      {"(lo", {"(loop "}},
      {"(loo", {"(loop "}},
      {"(loop", {"(loop "}},

      {"(m",
       {"(macro ", "(mem-new ", "(mem-del ", "(mem-cpy ", "(mem-load ",
        "(mem-is-set ", "(map ", "(match "}},
      {"(ma", {"(macro ", "(map ", "(match "}},
      {"(mac", {"(macro "}},
      {"(macr", {"(macro "}},
      {"(macro", {"(macro "}},
      {"(map", {"(map "}},
      {"(mat", {"(match "}},
      {"(matc", {"(match "}},
      {"(match", {"(match "}},
      {"(me",
       {"(mem-new ", "(mem-del ", "(mem-cpy ", "(mem-load ", "(mem-is-set "}},
      {"(mem",
       {"(mem-new ", "(mem-del ", "(mem-cpy ", "(mem-load ", "(mem-is-set "}},
      {"(mem-",
       {"(mem-new ", "(mem-del ", "(mem-cpy ", "(mem-load ", "(mem-is-set "}},
      {"(mem-n", {"(mem-new "}},
      {"(mem-ne", {"(mem-new "}},
      {"(mem-new", {"(mem-new "}},
      {"(mem-d", {"(mem-del "}},
      {"(mem-de", {"(mem-del "}},
      {"(mem-del", {"(mem-del "}},
      {"(mem-c", {"(mem-cpy "}},
      {"(mem-cp", {"(mem-cpy "}},
      {"(mem-cpy", {"(mem-cpy "}},
      {"(mem-l", {"(mem-load "}},
      {"(mem-lo", {"(mem-load "}},
      {"(mem-loa", {"(mem-load "}},
      {"(mem-load", {"(mem-load "}},
      {"(mem-i", {"(mem-is-set "}},
      {"(mem-is", {"(mem-is-set "}},
      {"(mem-is-", {"(mem-is-set "}},
      {"(mem-is-s", {"(mem-is-set "}},
      {"(mem-is-se", {"(mem-is-set "}},
      {"(mem-is-set", {"(mem-is-set "}},

      {"(n", {"(nop ", "(not ", "(neq ", "(never "}},
      {"(ne", {"(neq ", "(never "}},
      {"(neq", {"(neq "}},
      {"(nev", {"(never "}},
      {"(neve", {"(never "}},
      {"(never", {"(never "}},
      {"(no", {"(nop ", "(not "}},
      {"(nop", {"(nop"}},
      {"(not", {"(not "}},

      {"(o", {"(or "}},
      {"(or", {"(or "}},

      {"(q", {"(quote "}},
      {"(qu", {"(quote "}},
      {"(quo", {"(quote "}},
      {"(quot", {"(quote "}},
      {"(quote", {"(quote "}},

      {"(s",
       {"(set ", "(str ", "(split ", "(str-set-at ", "(strict_eq ",
        "(string_split ", "(sym_exists "}},
      {"(se", {"(set "}},
      {"(set", {"(set "}},
      {"(sp", {"(split "}},
      {"(spl", {"(split "}},
      {"(spli", {"(split "}},
      {"(split", {"(split "}},
      {"(st", {"(str ", "(str-set-at ", "(strict_eq ", "(string_split "}},
      {"(str", {"(str ", "(str-set-at ", "(strict_eq ", "(string_split "}},
      {"(str-", {"(str-set-at "}},
      {"(str-s", {"(str-set-at "}},
      {"(str-se", {"(str-set-at "}},
      {"(str-set", {"(str-set-at "}},
      {"(str-set-", {"(str-set-at "}},
      {"(str-set-a", {"(str-set-at "}},
      {"(str-set-at", {"(str-set-at "}},
      {"(stri", {"(strict_eq ", "(string_split "}},
      {"(stric", {"(strict_eq "}},
      {"(strict", {"(strict_eq "}},
      {"(strict_", {"(strict_eq "}},
      {"(strict_e", {"(strict_eq "}},
      {"(strict_eq", {"(strict_eq "}},
      {"(strin", {"(string_split "}},
      {"(string", {"(string_split "}},
      {"(string_", {"(string_split "}},
      {"(string_s", {"(string_split "}},
      {"(string_sp", {"(string_split "}},
      {"(string_spl", {"(string_split "}},
      {"(string_spli", {"(string_split "}},
      {"(string_split", {"(string_split "}},
      {"(sy", {"(sym_exists "}},
      {"(sym", {"(sym_exists "}},
      {"(sym_", {"(sym_exists "}},
      {"(sym_e", {"(sym_exists "}},
      {"(sym_ex", {"(sym_exists "}},
      {"(sym_exi", {"(sym_exists "}},
      {"(sym_exis", {"(sym_exists "}},
      {"(sym_exist", {"(sym_exists "}},
      {"(sym_exists", {"(sym_exists "}},

      {"(t", {"(throw ", "(try ", "(type "}},
      {"(th", {"(throw "}},
      {"(thr", {"(throw "}},
      {"(thro", {"(throw "}},
      {"(throw", {"(throw "}},
      {"(tr", {"(try "}},
      {"(try", {"(try "}},
      {"(ty", {"(type "}},
      {"(typ", {"(type "}},
      {"(type", {"(type "}},

      {"(u", {"(use \"", "(u8 ", "(u16 ", "(u32 ", "(u64 "}},
      {"(u8", {"(u8 "}},
      {"(u1", {"(u16 "}},
      {"(u16", {"(u16 "}},
      {"(u3", {"(u32 "}},
      {"(u32", {"(u32 "}},
      {"(u6", {"(u64 "}},
      {"(u64", {"(u64 "}},
      {"(us", {"(use \""}},
      {"(use", {"(use \""}},

      {"(w", {"(while "}},
      {"(wh", {"(while "}},
      {"(whi", {"(while "}},
      {"(whil", {"(while "}},
      {"(while", {"(while "}},

      {"(<", {"(<- ", "(<|> "}},
      {"(<-", {"(<- "}},
      {"(<|", {"(<|> "}},
      {"(<|>", {"(<|> "}},

      {"(>", {"(>| "}},
      {"(>|", {"(>| "}},

      {"(|", {"(|< ", "(|>> "}},
      {"(|<", {"(|< "}},
      {"(|>", {"(|>> "}},
      {"(|>>", {"(|>> "}},

      {"(<<", {"(<<| "}},
      {"(<<|", {"(<<| "}},

      {"(+", {"(+ "}},
      {"(-", {"(- "}},
      {"(*", {"(* ", "(** "}},
      {"(**", {"(** "}},
      {"(/", {"(/ "}},
      {"(%", {"(% "}},

      {"(>", {"(> ", "(>= ", "(>| "}},
      {"(>=", {"(>= "}},
      {"(>=", {"(>= "}},

      {"(<", {"(< ", "(<= ", "(<- ", "(<|> ", "(<<| "}},
      {"(<=", {"(<= "}},
  };
}

} // namespace completions
} // namespace app
